### ISSUE TITLE
Clicking cancel still triggers a callback

### ISSUE THREAD

**Issue by elewin** [petruisfan/ionic-monthpicker#11]
Clicking cancel still triggers a callback, which will result in junk data being sent out. The fix is easy, just add a call back to the cancel button that returns true to indicate that the cancel button was clicked, and then in the popup.then block check to see if res is true (indicating that the cancel button was clicked) and bail out without firing callback() :

`               

               
                var popup = $ionicPopup.show({
                    templateUrl: "monthpicker.html",
                    title: scope.title,
                    scope: scope,
                    buttons: [
                        {
                            text: scope.cancelText,
                            type: scope.cancelClass,
                            onTap: function(e){
                              return true;
                            }
                        }
                    ]
                });
                popup.then(function(res) {
                  if(res){
                    return null;
                  }
                    //return clone obj not internal private obj
                    callback({
                        year : scope.selection.year,
                        month : scope.selection.month
                    });
                });
`

**Comment by petruisfan** [comment]
Can you submit a pull request with this change? :)

**Comment by elewin** [comment]
I've created a pull request, pull request #12

**Comment by ShuangGod** [comment]
I get the same question too!

**Comment by ShuangGod** [comment]
scope.changeYear = function(index) {
          scope.selection.year += index;
 };

This code is the reason

**Comment by ShuangGod** [comment]
We need a price judgment

**Comment by ShuangGod** [comment]
popup.then(function(res) {
              if(res){
                return null;
              }
                //return clone obj not internal private obj
                callback({
                    year : scope.selection.year,
                    month : scope.selection.month
                });
            });
