### ISSUE TITLE
disable months

### ISSUE THREAD

**Issue by youassi** [petruisfan/ionic-monthpicker#6]

**Comment by petruisfan** [comment]
Can you elaborate?

**Comment by youassi** [comment]
Hey Petruisfan thanks for this library ,, could you please explain how I can disable months like in the screenshot.

**Comment by petruisfan** [comment]
Try "minMonthIndex" and "minYear" :) See table in readme

**Comment by youassi** [comment]
Thank you, Actually I'm working on disabling month for specific years have you any idea, I want to pass ana array of objects like this [{year:2016, months:[0,1,3,6]},  {year:2017, months:[5,1,3,11]}]

**Comment by petruisfan** [comment]
This is not currently possible. But feel free to submit a pull request :)
